name: qe-mini-example
channels:
  - conda-forge
dependencies:
  - python=3.8
  - sphinx
  - pip
  - pandas
  - altair
  - jupyterlab
  - pip:
    - quantecon
    - jupyter-book
    - sphinx-inline-tabs
    - vega_datasets
