name: styleguide
channels:
  - conda-forge
dependencies:
  - python=3.8
  - sphinx
  - pip
  - pandas
  - altair
  - jupyterlab
  - r-base
  - r-tidyverse
  - r-irkernel
  - r-ggalt
  - r-devtools
  - pip:
    - nbformat
    - jupyter-book
    - sphinx-inline-tabs
    - vega_datasets
