name: styleguide
channels:
  - conda-forge
dependencies:
  - python=3.8
  - sphinx
  - pip
  - pandas
  - altair
  - jupyterlab
  - r-base
  - r-tidyverse
  - pip:
    - quantecon
    - jupyter-book
    - sphinx-inline-tabs
    - vega_datasets
