#######################################################################################
# Book settings
title : Alluma Data Visualization Style Guide
author: Alluma Data Team
logo: 'data-program-icon.png'
favicon: 'data-program-icon.png'

# Information about where the book exists on the web
description: >-
  Alluma's data visualization style guide.

#######################################################################################
# Execution settings
execute:
  execute_notebooks           : cache

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar         : false
  use_repository_button       : true
  use_edit_page_button        : true
  use_issues_button           : true
  baseurl                     : "https://we-are-alluma.github.io/datavis-styleguide/"

# #######################################################################################
# Interact link settings
notebook_interface            : "notebook"

#######################################################################################
# Launch button settings
repository:
  url                         : https://github.com/we-are-alluma/datavis-styleguide
  path_to_book                : "mini_book"

binder:
  binderhub_url               : "https://mybinder.org"
  text                        : "Launch binder"

latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex

# ######################################################################################
# Sphinx
sphinx:
  extra_extensions:
  - sphinx_inline_tabs